# Iris Dataset Statistical Analysis Using NumPy

In [ ]:
import numpy as np

# Load CSV (skip header row)
iris = np.genfromtxt(
    "iris.csv",
    delimiter=",",
    skip_header=1,
    dtype=str
)

print(iris)

## Dataset Overview

In [2]:
print("Dimensions:",iris.ndim)
print("Shape:",iris.shape)
print("Size:",iris.size)
print("Datatype:",iris.dtype)

Dimensions: 2
Shape: (150, 6)
Size: 900
Datatype: <U15


##  Separate Features and Target Variable

In [3]:
# Features (Id ko skip karke)
X = iris[:, 1:5].astype(float)

# Species
y = iris[:, 5]

##  Feature Extraction

In [4]:
print("Features Shape :", X.shape)
print("Species Shape :", y.shape)

print("\nFirst 5 Feature Rows")
print(X[:5])

print("\nFirst 5 Species")
print(y[:5])

Features Shape : (150, 4)
Species Shape : (150,)

First 5 Feature Rows
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

First 5 Species
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [5]:
sepal_length = X[:, 0]
sepal_width = X[:, 1]
petal_length = X[:, 2]
petal_width = X[:, 3]
print("Sepal Length :", sepal_length[:5])
print("Sepal Width :", sepal_width[:5])
print("Petal Length :", petal_length[:5])
print("Petal Width :", petal_width[:5])

Sepal Length : [5.1 4.9 4.7 4.6 5. ]
Sepal Width : [3.5 3.  3.2 3.1 3.6]
Petal Length : [1.4 1.4 1.3 1.5 1.4]
Petal Width : [0.2 0.2 0.2 0.2 0.2]


##  Species Identification

In [6]:
print("Unique Species:")
print(np.unique(y))

Unique Species:
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


##  Boolean Indexing

In [7]:
setosa = X[y == "Iris-setosa"]
versicolor = X[y == "Iris-versicolor"]
virginica = X[y == "Iris-virginica"]

In [10]:
print("Setosa Shape :", setosa.shape)
print("Versicolor Shape :", versicolor.shape)
print("Virginica Shape :", virginica.shape)

Setosa Shape : (50, 4)
Versicolor Shape : (50, 4)
Virginica Shape : (50, 4)


In [11]:
print(setosa[:3])
print()

print(versicolor[:3])
print()

print(virginica[:3])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]

[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]]

[[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]]


##  Statistical Analysis

##  Species-wise Analysis

In [12]:
print("Setosa Mean")
print(np.mean(setosa, axis=0))

print()

print("Versicolor Mean")
print(np.mean(versicolor, axis=0))

print()

print("Virginica Mean")
print(np.mean(virginica, axis=0))

Setosa Mean
[5.006 3.418 1.464 0.244]

Versicolor Mean
[5.936 2.77  4.26  1.326]

Virginica Mean
[6.588 2.974 5.552 2.026]


In [13]:
print(np.median(setosa, axis=0))

print(np.median(versicolor, axis=0))

print(np.median(virginica, axis=0))

[5.  3.4 1.5 0.2]
[5.9  2.8  4.35 1.3 ]
[6.5  3.   5.55 2.  ]


In [14]:
print(np.std(setosa, axis=0))

print(np.std(versicolor, axis=0))

print(np.std(virginica, axis=0))

[0.34894699 0.37719491 0.17176728 0.10613199]
[0.51098337 0.31064449 0.46518813 0.19576517]
[0.62948868 0.31925538 0.54634787 0.27188968]


In [15]:
print(np.min(setosa, axis=0))

print(np.min(versicolor, axis=0))

print(np.min(virginica, axis=0))

[4.3 2.3 1.  0.1]
[4.9 2.  3.  1. ]
[4.9 2.2 4.5 1.4]


In [16]:
print(np.max(setosa, axis=0))

print(np.max(versicolor, axis=0))

print(np.max(virginica, axis=0))

[5.8 4.4 1.9 0.6]
[7.  3.4 5.1 1.8]
[7.9 3.8 6.9 2.5]


In [17]:
print("="*50)
print("OVERALL DATASET ANALYSIS")
print("="*50)

print("Mean :", np.mean(X, axis=0))
print("Median :", np.median(X, axis=0))
print("Standard Deviation :", np.std(X, axis=0))
print("Minimum :", np.min(X, axis=0))
print("Maximum :", np.max(X, axis=0))

OVERALL DATASET ANALYSIS
Mean : [5.84333333 3.054      3.75866667 1.19866667]
Median : [5.8  3.   4.35 1.3 ]
Standard Deviation : [0.82530129 0.43214658 1.75852918 0.76061262]
Minimum : [4.3 2.  1.  0.1]
Maximum : [7.9 4.4 6.9 2.5]


##  Maximum and Minimum Analysis

In [18]:
max_index = np.argmax(sepal_length)

print("Flower with Maximum Sepal Length")
print("Index :", max_index)
print("Species :", y[max_index])
print("Sepal Length :", sepal_length[max_index])

Flower with Maximum Sepal Length
Index : 131
Species : Iris-virginica
Sepal Length : 7.9


In [19]:
min_index = np.argmin(petal_width)

print("Flower with Minimum Petal Width")
print("Index :", min_index)
print("Species :", y[min_index])
print("Petal Width :", petal_width[min_index])

Flower with Minimum Petal Width
Index : 9
Species : Iris-setosa
Petal Width : 0.1


In [20]:
long_sepal = X[sepal_length > 7]

print("Flowers having Sepal Length > 7")
print(long_sepal)
print("Count :", len(long_sepal))

Flowers having Sepal Length > 7
[[7.1 3.  5.9 2.1]
 [7.6 3.  6.6 2.1]
 [7.3 2.9 6.3 1.8]
 [7.2 3.6 6.1 2.5]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [7.7 2.8 6.7 2. ]
 [7.2 3.2 6.  1.8]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [7.7 3.  6.1 2.3]]
Count : 12


## Random Sampling

In [21]:
np.random.seed(42)

sample = np.random.choice(len(X), 5, replace=False)

print("Random Flower Indexes")
print(sample)

print("\nRandom Flower Data")
print(X[sample])

print("\nSpecies")
print(y[sample])

Random Flower Indexes
[ 73  18 118  78  76]

Random Flower Data
[[6.1 2.8 4.7 1.2]
 [5.7 3.8 1.7 0.3]
 [7.7 2.6 6.9 2.3]
 [6.  2.9 4.5 1.5]
 [6.8 2.8 4.8 1.4]]

Species
['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor']


##  Sorting Feature Values

In [22]:
sorted_sepal = np.sort(sepal_length)

print("Smallest 10 Sepal Lengths")
print(sorted_sepal[:10])

print()

print("Largest 10 Sepal Lengths")
print(sorted_sepal[-10:])

Smallest 10 Sepal Lengths
[4.3 4.4 4.4 4.4 4.5 4.6 4.6 4.6 4.6 4.7]

Largest 10 Sepal Lengths
[7.2 7.2 7.3 7.4 7.6 7.7 7.7 7.7 7.7 7.9]


##  Key Insights

In [23]:
print("="*60)
print("IRIS DATASET INSIGHTS")
print("="*60)

print("1. Total Flowers :", len(X))
print("2. Total Features :", X.shape[1])
print("3. Species :", np.unique(y))

print("4. Average Sepal Length :", np.mean(sepal_length))
print("5. Average Petal Length :", np.mean(petal_length))

print("6. Maximum Sepal Length :", np.max(sepal_length))
print("7. Minimum Sepal Length :", np.min(sepal_length))

print("8. Maximum Petal Width :", np.max(petal_width))
print("9. Minimum Petal Width :", np.min(petal_width))

IRIS DATASET INSIGHTS
1. Total Flowers : 150
2. Total Features : 4
3. Species : ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
4. Average Sepal Length : 5.843333333333334
5. Average Petal Length : 3.758666666666666
6. Maximum Sepal Length : 7.9
7. Minimum Sepal Length : 4.3
8. Maximum Petal Width : 2.5
9. Minimum Petal Width : 0.1


In [24]:
setosa_mean = np.mean(setosa[:,0])
versicolor_mean = np.mean(versicolor[:,0])
virginica_mean = np.mean(virginica[:,0])

print("Setosa :", setosa_mean)
print("Versicolor :", versicolor_mean)
print("Virginica :", virginica_mean)

Setosa : 5.006
Versicolor : 5.936
Virginica : 6.587999999999998


In [25]:
print(np.mean(setosa[:,2]))
print(np.mean(versicolor[:,2]))
print(np.mean(virginica[:,2]))

1.464
4.26
5.5520000000000005


In [26]:
print("Setosa :", len(setosa))
print("Versicolor :", len(versicolor))
print("Virginica :", len(virginica))

Setosa : 50
Versicolor : 50
Virginica : 50


##  Save Analysis Results

In [27]:
with open("analysis_results.txt","w") as file:

    file.write("IRIS DATASET ANALYSIS\n\n")

    file.write(f"Total Flowers : {len(X)}\n")

    file.write(f"Total Features : {X.shape[1]}\n")

    file.write(f"Species : {np.unique(y)}\n")

    file.write(f"Average Sepal Length : {np.mean(sepal_length)}\n")

    file.write(f"Average Petal Length : {np.mean(petal_length)}\n")